package com.zatarana.vivopreco;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.text.*;
import java.util.*;

public class MainActivity extends Activity {
    private static final String PREF = "vivopreco";
    private static final String TASKS = "tasks";
    private static final String TXS = "transactions";
    private static final String DEBTS = "debts";
    private static final String GOALS = "goals";
    private SharedPreferences db;
    private LinearLayout root, nav;
    private FrameLayout content;
    private String tab = "inicio";
    private final Locale br = new Locale("pt", "BR");
    private final NumberFormat money = NumberFormat.getCurrencyInstance(br);
    private final SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy", br);
    private final int BLUE = Color.rgb(37,99,235), GREEN = Color.rgb(22,163,74), RED = Color.rgb(220,38,38), AMBER = Color.rgb(217,119,6), TEXT = Color.rgb(15,23,42), MUTED = Color.rgb(100,116,139), BG = Color.rgb(248,250,252);

    @Override public void onCreate(Bundle b){ super.onCreate(b); db=getSharedPreferences(PREF,MODE_PRIVATE); seed(); shell(); showInicio(); }

    private void shell(){
        root = new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setBackgroundColor(BG);
        content = new FrameLayout(this); root.addView(content,new LinearLayout.LayoutParams(-1,0,1));
        nav = new LinearLayout(this); nav.setOrientation(LinearLayout.HORIZONTAL); nav.setPadding(dp(8),dp(6),dp(8),dp(6)); nav.setBackgroundColor(Color.WHITE); root.addView(nav,new LinearLayout.LayoutParams(-1,-2));
        setContentView(root); drawNav();
    }
    private void drawNav(){ nav.removeAllViews(); btnNav("inicio","Início"); btnNav("tarefas","Tarefas"); btnNav("financas","Finanças"); btnNav("dividas","Dívidas"); btnNav("mais","Mais"); }
    private void btnNav(final String id,String label){ Button b=new Button(this); b.setText(label); b.setAllCaps(false); b.setTextSize(12); b.setTextColor(id.equals(tab)?Color.WHITE:TEXT); b.setBackground(round(id.equals(tab)?BLUE:Color.rgb(241,245,249),16,0)); b.setOnClickListener(v->{ tab=id; drawNav(); if(id.equals("inicio"))showInicio(); if(id.equals("tarefas"))showTarefas(); if(id.equals("financas"))showFinancas(); if(id.equals("dividas"))showDividas(); if(id.equals("mais"))showMais(); }); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(46),1); lp.setMargins(dp(3),0,dp(3),0); nav.addView(b,lp); }
    private LinearLayout page(String title,String sub){ content.removeAllViews(); ScrollView sv=new ScrollView(this); LinearLayout p=new LinearLayout(this); p.setOrientation(LinearLayout.VERTICAL); p.setPadding(dp(18),dp(18),dp(18),dp(24)); sv.addView(p); TextView h=txt(title,26,Typeface.BOLD,TEXT); p.addView(h); if(sub!=null){ TextView s=txt(sub,14,Typeface.NORMAL,MUTED); s.setPadding(0,dp(4),0,dp(12)); p.addView(s); } content.addView(sv); return p; }

    private void showInicio(){ tab="inicio"; drawNav(); LinearLayout p=page("VivoPreco","App local para tarefas, finanças, dívidas e metas. Build debug automático pelo GitHub Actions."); double inc=sum("receita"), exp=sum("despesa"), bal=inc-exp; LinearLayout r=new LinearLayout(this); r.setOrientation(LinearLayout.HORIZONTAL); p.addView(r); r.addView(metric("Saldo",money.format(bal),bal>=0?GREEN:RED),new LinearLayout.LayoutParams(0,-2,1)); r.addView(metric("Tarefas",done()+"/"+arr(TASKS).length(),BLUE),new LinearLayout.LayoutParams(0,-2,1)); p.addView(card("Resumo financeiro","Receitas: "+money.format(inc)+"\nDespesas: "+money.format(exp)+"\nResultado: "+money.format(bal),bal>=0?GREEN:RED)); p.addView(card("Dívidas",arr(DEBTS).length()+" registro(s) acompanhado(s).",AMBER)); p.addView(action("+ Nova tarefa",v->taskDialog())); p.addView(action("+ Nova transação",v->txDialog())); p.addView(action("+ Nova dívida",v->debtDialog())); p.addView(action("+ Nova meta",v->goalDialog())); }
    private void showTarefas(){ tab="tarefas"; drawNav(); LinearLayout p=page("Tarefas","Toque para concluir. Segure para apagar."); p.addView(action("+ Adicionar tarefa",v->taskDialog())); JSONArray a=arr(TASKS); if(a.length()==0){ p.addView(empty("Nenhuma tarefa.")); return;} for(int i=0;i<a.length();i++){ JSONObject o=a.optJSONObject(i); if(o==null)continue; boolean ok=o.optBoolean("done"); LinearLayout c=box(ok?Color.rgb(241,245,249):Color.WHITE,ok?MUTED:BLUE); c.addView(txt((ok?"✓ ":"○ ")+o.optString("title"),18,Typeface.BOLD,ok?MUTED:TEXT)); c.addView(txt("Prioridade: "+o.optString("priority")+" • Prazo: "+o.optString("due"),13,0,MUTED)); final int x=i; c.setOnClickListener(v->{ try{ o.put("done",!ok); save(TASKS,a); showTarefas(); }catch(Exception e){err(e);} }); c.setOnLongClickListener(v->{ del(TASKS,x); showTarefas(); return true; }); p.addView(c);} }
    private void showFinancas(){ tab="financas"; drawNav(); LinearLayout p=page("Finanças","Receitas e despesas com saldo automático."); p.addView(action("+ Adicionar transação",v->txDialog())); p.addView(card("Saldo atual",money.format(sum("receita")-sum("despesa")),BLUE)); p.addView(card("Receitas",money.format(sum("receita")),GREEN)); p.addView(card("Despesas",money.format(sum("despesa")),RED)); p.addView(title("Histórico")); JSONArray a=arr(TXS); if(a.length()==0){p.addView(empty("Nenhuma transação."));return;} for(int i=a.length()-1;i>=0;i--){ JSONObject o=a.optJSONObject(i); if(o==null)continue; boolean rec=o.optString("type").equals("receita"); LinearLayout c=box(Color.WHITE,rec?GREEN:RED); c.addView(txt((rec?"+ ":"- ")+money.format(o.optDouble("value")),20,Typeface.BOLD,rec?GREEN:RED)); c.addView(txt(o.optString("desc")+" • "+o.optString("category")+" • "+o.optString("date"),13,0,MUTED)); final int x=i; c.setOnLongClickListener(v->{ del(TXS,x); showFinancas(); return true; }); p.addView(c);} }
    private void showDividas(){ tab="dividas"; drawNav(); LinearLayout p=page("Dívidas","Controle saldo devedor e registre pagamentos."); p.addView(action("+ Cadastrar dívida",v->debtDialog())); JSONArray a=arr(DEBTS); double total=0; for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i); if(o!=null)total+=Math.max(0,o.optDouble("total")-o.optDouble("paid"));} p.addView(card("Saldo devedor total",money.format(total),AMBER)); if(a.length()==0){p.addView(empty("Nenhuma dívida."));return;} for(int i=0;i<a.length();i++){ JSONObject o=a.optJSONObject(i); if(o==null)continue; double rest=Math.max(0,o.optDouble("total")-o.optDouble("paid")); LinearLayout c=box(Color.WHITE,rest==0?GREEN:AMBER); c.addView(txt(o.optString("name"),18,Typeface.BOLD,TEXT)); c.addView(txt("Credor: "+o.optString("creditor"),13,0,MUTED)); c.addView(txt("Pago: "+money.format(o.optDouble("paid"))+" • Restante: "+money.format(rest),13,0,rest==0?GREEN:MUTED)); final int x=i; c.setOnClickListener(v->payDebt(x)); c.setOnLongClickListener(v->{del(DEBTS,x); showDividas(); return true;}); p.addView(c);} }
    private void showMais(){ tab="mais"; drawNav(); LinearLayout p=page("Mais","Metas e relatório rápido."); p.addView(action("+ Nova meta",v->goalDialog())); JSONArray a=arr(GOALS); if(a.length()==0)p.addView(empty("Nenhuma meta.")); for(int i=0;i<a.length();i++){ JSONObject o=a.optJSONObject(i); if(o==null)continue; double target=o.optDouble("target"), cur=o.optDouble("current"); int pc=target<=0?0:(int)Math.min(100,Math.round(cur/target*100)); LinearLayout c=box(Color.WHITE,GREEN); c.addView(txt(o.optString("name"),18,Typeface.BOLD,TEXT)); c.addView(txt(money.format(cur)+" de "+money.format(target)+" • "+pc+"%",13,0,MUTED)); final int x=i; c.setOnClickListener(v->contribGoal(x)); c.setOnLongClickListener(v->{del(GOALS,x); showMais(); return true;}); p.addView(c);} p.addView(title("Relatório rápido")); p.addView(card("Produtividade",done()+" tarefas concluídas de "+arr(TASKS).length(),BLUE)); p.addView(card("Fluxo",money.format(sum("receita")-sum("despesa")),GREEN)); p.addView(danger("Resetar dados locais",v->reset())); }

    private void taskDialog(){ LinearLayout f=form(); EditText t=input("Título"); EditText d=input("Prazo"); EditText pr=input("Prioridade"); f.addView(t);f.addView(d);f.addView(pr); new AlertDialog.Builder(this).setTitle("Nova tarefa").setView(f).setNegativeButton("Cancelar",null).setPositiveButton("Salvar",(x,w)->{try{append(TASKS,new JSONObject().put("title",safe(t,"Nova tarefa")).put("due",safe(d,"Sem data")).put("priority",safe(pr,"Média")).put("done",false)); refresh();}catch(Exception e){err(e);}}).show();}
    private void txDialog(){ LinearLayout f=form(); RadioGroup g=new RadioGroup(this); g.setOrientation(RadioGroup.HORIZONTAL); RadioButton de=new RadioButton(this); de.setText("Despesa"); de.setId(1); RadioButton re=new RadioButton(this); re.setText("Receita"); re.setId(2); g.addView(de);g.addView(re);g.check(1); EditText val=input("Valor"); EditText desc=input("Descrição"); EditText cat=input("Categoria"); f.addView(g);f.addView(val);f.addView(desc);f.addView(cat); new AlertDialog.Builder(this).setTitle("Nova transação").setView(f).setNegativeButton("Cancelar",null).setPositiveButton("Salvar",(x,w)->{try{append(TXS,new JSONObject().put("type",g.getCheckedRadioButtonId()==2?"receita":"despesa").put("value",num(val)).put("desc",safe(desc,"Sem descrição")).put("category",safe(cat,"Geral")).put("date",df.format(new Date()))); refresh();}catch(Exception e){err(e);}}).show();}
    private void debtDialog(){ LinearLayout f=form(); EditText n=input("Nome"); EditText c=input("Credor"); EditText t=input("Valor total"); EditText p=input("Valor pago"); f.addView(n);f.addView(c);f.addView(t);f.addView(p); new AlertDialog.Builder(this).setTitle("Cadastrar dívida").setView(f).setNegativeButton("Cancelar",null).setPositiveButton("Salvar",(x,w)->{try{append(DEBTS,new JSONObject().put("name",safe(n,"Dívida")).put("creditor",safe(c,"Não informado")).put("total",num(t)).put("paid",num(p))); refresh();}catch(Exception e){err(e);}}).show();}
    private void goalDialog(){ LinearLayout f=form(); EditText n=input("Meta"); EditText t=input("Valor alvo"); EditText c=input("Valor atual"); f.addView(n);f.addView(t);f.addView(c); new AlertDialog.Builder(this).setTitle("Nova meta").setView(f).setNegativeButton("Cancelar",null).setPositiveButton("Salvar",(x,w)->{try{append(GOALS,new JSONObject().put("name",safe(n,"Meta")).put("target",num(t)).put("current",num(c))); refresh();}catch(Exception e){err(e);}}).show();}
    private void payDebt(int idx){ JSONArray a=arr(DEBTS); JSONObject o=a.optJSONObject(idx); if(o==null)return; EditText v=input("Valor pago agora"); new AlertDialog.Builder(this).setTitle("Registrar pagamento").setView(v).setNegativeButton("Cancelar",null).setPositiveButton("Salvar",(d,w)->{try{ double n=num(v); o.put("paid",o.optDouble("paid")+n); save(DEBTS,a); append(TXS,new JSONObject().put("type","despesa").put("value",n).put("desc","Pagamento de dívida: "+o.optString("name")).put("category","Dívidas").put("date",df.format(new Date()))); showDividas();}catch(Exception e){err(e);}}).show();}
    private void contribGoal(int idx){ JSONArray a=arr(GOALS); JSONObject o=a.optJSONObject(idx); if(o==null)return; EditText v=input("Contribuição"); new AlertDialog.Builder(this).setTitle("Contribuir").setView(v).setNegativeButton("Cancelar",null).setPositiveButton("Salvar",(d,w)->{try{o.put("current",o.optDouble("current")+num(v)); save(GOALS,a); showMais();}catch(Exception e){err(e);}}).show();}

    private void seed(){ if(db.contains(TASKS))return; try{ save(TASKS,new JSONArray().put(new JSONObject().put("title","Revisar orçamento do mês").put("due","Hoje").put("priority","Alta").put("done",false))); save(TXS,new JSONArray().put(new JSONObject().put("type","receita").put("value",1500).put("desc","Entrada inicial").put("category","Receita").put("date",df.format(new Date())))); save(DEBTS,new JSONArray()); save(GOALS,new JSONArray()); }catch(Exception e){err(e);} }
    private JSONArray arr(String k){ try{return new JSONArray(db.getString(k,"[]"));}catch(Exception e){return new JSONArray();} }
    private void save(String k,JSONArray a){ db.edit().putString(k,a.toString()).apply(); }
    private void append(String k,JSONObject o){ JSONArray a=arr(k); a.put(o); save(k,a); }
    private void del(String k,int idx){ JSONArray a=arr(k),b=new JSONArray(); for(int i=0;i<a.length();i++) if(i!=idx)b.put(a.opt(i)); save(k,b); }
    private double sum(String type){ JSONArray a=arr(TXS); double s=0; for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i); if(o!=null&&type.equals(o.optString("type")))s+=o.optDouble("value");} return s; }
    private int done(){ JSONArray a=arr(TASKS); int c=0; for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i); if(o!=null&&o.optBoolean("done"))c++;} return c; }
    private void refresh(){ if(tab.equals("inicio"))showInicio(); else if(tab.equals("tarefas"))showTarefas(); else if(tab.equals("financas"))showFinancas(); else if(tab.equals("dividas"))showDividas(); else showMais(); }
    private void reset(){ new AlertDialog.Builder(this).setTitle("Resetar dados?").setMessage("Apaga os dados locais deste aparelho.").setNegativeButton("Cancelar",null).setPositiveButton("Resetar",(d,w)->{db.edit().clear().apply();seed();showMais();}).show(); }
    private double num(EditText e){ String s=e.getText().toString().replace("R$","").replace(".","").replace(",",".").trim(); if(s.isEmpty())return 0; try{return Double.parseDouble(s);}catch(Exception ex){return 0;} }
    private String safe(EditText e,String f){ String s=e.getText().toString().trim(); return s.isEmpty()?f:s; }
    private LinearLayout form(){ LinearLayout f=new LinearLayout(this); f.setOrientation(LinearLayout.VERTICAL); f.setPadding(dp(8),dp(8),dp(8),0); return f; }
    private EditText input(String h){ EditText e=new EditText(this); e.setHint(h); e.setSingleLine(true); e.setTextSize(15); e.setPadding(dp(8),dp(6),dp(8),dp(6)); return e; }
    private TextView txt(String s,int sp,int st,int color){ TextView t=new TextView(this); t.setText(s); t.setTextSize(sp); t.setTypeface(Typeface.DEFAULT,st); t.setTextColor(color); t.setLineSpacing(0,1.08f); return t; }
    private TextView title(String s){ TextView t=txt(s,18,Typeface.BOLD,TEXT); t.setPadding(0,dp(18),0,dp(4)); return t; }
    private TextView empty(String s){ TextView t=txt(s,14,0,MUTED); t.setGravity(Gravity.CENTER); t.setPadding(dp(12),dp(24),dp(12),dp(24)); return t; }
    private LinearLayout metric(String l,String v,int color){ LinearLayout c=box(Color.WHITE,color); c.addView(txt(l,12,Typeface.BOLD,MUTED)); c.addView(txt(v,20,Typeface.BOLD,color)); return c; }
    private LinearLayout card(String h,String b,int color){ LinearLayout c=box(Color.WHITE,color); c.addView(txt(h,17,Typeface.BOLD,TEXT)); TextView body=txt(b,14,0,MUTED); body.setPadding(0,dp(6),0,0); c.addView(body); return c; }
    private LinearLayout box(int bgc,int stroke){ LinearLayout c=new LinearLayout(this); c.setOrientation(LinearLayout.VERTICAL); c.setPadding(dp(16),dp(14),dp(16),dp(14)); c.setBackground(round(bgc,18,stroke)); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2); lp.setMargins(0,dp(8),0,dp(8)); c.setLayoutParams(lp); return c; }
    private Button action(String s,View.OnClickListener l){ Button b=new Button(this); b.setText(s); b.setAllCaps(false); b.setTextColor(Color.WHITE); b.setTextSize(15); b.setTypeface(Typeface.DEFAULT,Typeface.BOLD); b.setBackground(round(BLUE,18,0)); b.setOnClickListener(l); b.setLayoutParams(new LinearLayout.LayoutParams(-1,dp(50))); return b; }
    private Button danger(String s,View.OnClickListener l){ Button b=action(s,l); b.setTextColor(RED); b.setBackground(round(Color.rgb(254,242,242),18,RED)); return b; }
    private GradientDrawable round(int color,int r,int stroke){ GradientDrawable g=new GradientDrawable(); g.setColor(color); g.setCornerRadius(dp(r)); if(stroke!=0)g.setStroke(dp(1),stroke); return g; }
    private int dp(int v){ return (int)(v*getResources().getDisplayMetrics().density+.5f); }
    private void err(Exception e){ Toast.makeText(this,"Erro: "+e.getMessage(),Toast.LENGTH_LONG).show(); }
}
